meta_product_name: "Presidential Raise"
meta_title: "Presidential Raise"
meta_description: "Politics is a Money Game. A jacket with the patches of the candidate's supporters."
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@presraise"   # required for Twitter Cards
